### ISSUE TITLE
Recipient Key must be specific to current message

### ISSUE THREAD

**Issue by keks** [ssbc/envelope-spec#1]
The recipient key may not be the immediate shared key between the sender and a recipient, or of a group the sender/recipient is in. Otherwise, it would be trivial for other recipients to compute your shared secret:

```
msg_key XOR shared_secret_alice_bob
msg_key XOR shared_secret_alice_carol
```
Now Carol could figure out the secret shared by Alice and Bob by computing the message key and xoring it to the first slot. Then, they could decrypt other messages as well.

To prevent this, a message-specific shared secret must be derived, e.g. by including the `previous` hash in the key derivation:

```
msg_key XOR HMAC(shared_secret_alice_bob, "msg_slot_key;prev=%....sha256")
msg_key XOR HMAC(shared_secret_alice_carol, "msg_slot_key;prev=%....sha256")
```

Note that the derivation also needs to contain the purpose of the key, such that it's not possible to perform the same derivation operation with two different intentions. It might even be good to not use HMAC but HKDF with a salt value that we choose for the specs.

**Comment by mixmix** [comment]
I've been looking at this for `hkdf.expand` in javascript

https://www.npmjs.com/package/futoin-hkdf#hkdfexpandhash-hash_len-prk-length-info-%E2%87%92-buffer

**Comment by dominictarr** [comment]
yes. very good catch!

@mixmix also pointed out (we are on a call right now) that on the very first message, previous is null. so multiple feeds would hmac with the same value. This edge case would be very hard to hit in practice - at most only mean you could decrypt the first message in a feed, if it's a encrypted.

if alice encrypts her first message to bob and carol, and then carol encrypts her first message to alice, bob could read it.

A solution though, since there is no previous hash on the first message, to use the public key of the feed as the external nonce for that message.

**Comment by dominictarr** [comment]
or to disallow private messages on the first message? I think using public key as external nonce is better though.

**Comment by keks** [comment]
Why not use both values together? There only is one first message for every feed, so only one instance of `(@someFeed, null)`.

We just need to find a good encoding for these two values. My understanding is that this is safe if there is a bijection between the encoded version and the logical value, i.e. there is just one encoding and the encoded version could be parsed unambiguously.

The simplest way would probably be to length-prefix and then concatenate them, but I'm not sure that is the best solution from a perspective of clarity. Maybe bencode?

**Comment by dominictarr** [comment]
@keks I also suggested that! that's a nice way to do it because you can verify that the implementation also supports this edgecase just by looking at the spec, because it won't work for the other uses if they don't support it.

**Comment by mixmix** [comment]
PR open which resolves this
