### ISSUE TITLE
box test vectors: message and feed ids should have proper format

### ISSUE THREAD

**Issue by keks** [ssbc/envelope-spec#13]
Currently, they are just some base64 data. I have a few issues with this:
1. If they had a sigil and format, it would immediately be clear what they are. Now they are just random data.
2. We use the feed and message format in the derivation, so they need to be passed in instead of hardcoded in the tests.
3. It seems they are too long? My base64 parser complains that they are 33 byte and the destination buffer is just 32 byte long. The parsing works when I replace the last character with a `=`, but then the decrypt tests fail. Maybe my implementation is wrong, but it's likely that it is because the values changed.

**Comment by keks** [comment]
This also applies to the unbox and derive_secret test vectors.

**Comment by keks** [comment]
Oohhh, I think I get it. The strings are already in the binary format proposed by aljoscha, right?

Hm, I still feel like we should use the readable string version here and do the conversion internally. That way the test vectors are more understandable and we also have coverage for the tfk conversion.

**Comment by mixmix** [comment]
correct, these vectors _should_ be in the tfk format .. which means they should be 34 bytes: 
- type (1 byte)
- format (1 byte)
- key for thing (32 bytes in ssb case)

Looks like vectors might be broken, let me have a look

**Comment by mixmix** [comment]
Pushed up fixed vectors @keks 

e.g. 

```
> var b = Buffer.from('AQB/nWfNgPjvp3uNL4zhpqdT74q21YlZA7f8wdWqxHXtKw==', 'base64')
> b
<Buffer 01 00 7f 9d 67 cd 80 f8 ef a7 7b 8d 2f 8c e1 a6 a7 53 ef 8a b6 d5 89 59 03 b7 fc c1 d5 aa c4 75 ed 2b>
> b.length
34
```
---

I agree TFK should get test coverage. I disagree with doing it in this test. Reasons:
- all our vectors so far have been Buffers (encoded to base64 strings)
- the details of the coding are quite specific to where this is used (e.g. scuttlebutt), whereas this module is more general

**Another way of asking this is** : 
Do you think the API of this should take `feed_id` as :
- A) a Buffer, already TFK encoded with whatever type/ format codes you're working with
- B) some Object like `{ type, format, key }`

---

_p.s. this is not Aljoscha's format (he didn't have one of this exactly), but I did get input from him and he wasn't upset with what I've proposed!_

**Comment by mixmix** [comment]
I think we agreed to close this.
Let me know if I'm wrong @keks
