### ISSUE TITLE
derive secret: previous message hash

### ISSUE THREAD

**Issue by cryptix** [ssbc/envelope-spec#17]
Apart from feeling a bit ssb specific, I think it would be good practice to include a vector for the corner case of `sequence: 1` where `previous: null`.

What data will be used for previous then? empty buffer? zero bytes of the same length?

**Comment by mixmix** [comment]
I couldn't figure out where to put a test for this. The box / unbox supply a prev_msg_id in TFK encoding for you, so I don't think they're useful?

I think it's important to document for sure so here's a PR for that: https://github.com/ssbc/envelope-spec/pull/18

Questions:
- did I document it clearly + in the right place?
- do you think we need a test for this?

thanks @cryptix

**Comment by cryptix** [comment]
> do you think we need a test for this?

I think it would be cool to include this case in the vectors just for easier automation and knowing where to look if it fails but if it’s in the document at least the vector can be added later just as well.

**Comment by mixmix** [comment]
But the vector would be just a buffer ... and the box/unbox code only care about being given buffers and moving them around in the right way.
The thing I think we want to test is "does the person know how to read previous from a message and translate it into the correct buffer?"

To me this sounds like a TFK encoding vector?

**Comment by cryptix** [comment]
> the box/unbox code only care about being given buffers

yup, exactly but it expects them in certain way (or length) but like I said, I think this it is fine with #18 merged.
