### ISSUE TITLE
does hkdf use too many hashes?

### ISSUE THREAD

**Issue by dominictarr** [ssbc/envelope-spec#2]
I was looking at the spec https://tools.ietf.org/html/rfc5869 and https://github.com/futoin/util-js-hkdf/blob/master/hkdf.js#L97-L128

It _looks like_ it builds up the derived key, up to a length, by running hmac for every byte in the derived key. Since we are calling hkdf more than 5 times, and each one is 24 or 32 bytes, that's like hundreds of hmacs. Previously I measured the relative performance of hashes and asymmetric operations https://github.com/futoin/util-js-hkdf/blob/master/hkdf.js#L97-L128 and I discovered that 60 sha256 ops where the same as one signature. symmetric cryptography is fast, but if you do hundreds of them, they are slow again.

Since this design depends on trail decryption, i.e. everyone tries to decrypt every message, so I want a message not for you to to fail quickly.

I don't understand exactly what hkdf gives us over hmac. this stackexchange question https://crypto.stackexchange.com/questions/30459/why-does-hkdf-use-hmacsalt-key-instead-of-hmackey-salt/30461 the difference is that it's faster to bruteforce... but since we are always using a high entropy key, that is irrelevant.

> A Key  derivation  function  (KDF) is a basic and essential  component  of  cryptographic  systems:Its  goal  is  to  take  a source  of  initial  keying  material, _usually  containing  some  good  amount  of randomness, but not distributed uniformly or for which an attacker has some partial knowledge_, and  derive  from  it  one  or  more cryptographically strong secret keys.

_emphasis mine_ but in our case, we start with high entropy key, completely unknown to the attacker. We merely not reuse the key, so we are only trying to derive another equally good key.

It seems to me that a simple hmac should be more than enough for our case.

**Comment by mixmix** [comment]
Keks mentioned hkdf.expand

The module i was using for this suggested this is just half of the full hkdf algorithm, which could bring these costs down huh?

**Comment by dominictarr** [comment]
yes, but we should also avoid using non-standard primitives as that will make it harder for others to implement.

**Comment by keks** [comment]
> Since we are calling hkdf more than 5 times, and each one is 24 or 32 bytes, that's like hundreds of hmacs

Given that the keys we use are the same length as the hash function we use, 1 HKDF = 2 HMAC. If we use Expand, it's 1 HKDF-Expand = 1 HMAC.

So with `N` invocations of HKDF, we have `2N` invocations of HMAC, with HKDF-Expand we end up with `N` invocations of HMAC. each HMAC is 2 hashes.

>I don't understand exactly what hkdf gives us over hmac.

I was suggesting to use HKDF-Expand. That is a specific format of invoking HMAC. Same complexity.

> yes, but we should also avoid using non-standard primitives as that will make it harder for others to implement.

HKDF-Expand is not a non-standard primitive. It was well understood by the time that RFC was published, here is the accompanying paper: https://eprint.iacr.org/2010/264

**Comment by keks** [comment]
It's described very early on, actually: https://tools.ietf.org/html/rfc5869#section-2.2

The point of calling it "HKDF-Expand" instead of "HMAC" is mostly that it is used to expand keys, and not to compute a message authentication code. It's the same computation, but describes different security goals (pseudorandomness instead of unforgeability)

**Comment by mixmix** [comment]
We agreed on this in our latest meeting.
HKDF.expand is chill
